import teamLogos from "./teamLogos.js";

const styles = {
    toolbar: {
        display: "flex",
        justifyContent: "space-between",
        backgroundColor: '#1c1c1c',
    },
    nba: {
        color: 'white',
        fontSize: '30px',
        fontFamily: 'Poppins',
        textDecoration: 'none',
        marginRight: "auto",
    },
    footer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '150px',
        backgroundColor: '#1c1c1c',
        color: 'white',
        position: 'sticky',
        paddingLeft: '10%',
    },
    h1: {
        position: 'absolute',
        width: '100%',
        height: '100%',
        top: '0',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
        fontFamily: 'Poppins, sans-serif',
        textShadow: '2px 2px 4px rgba(0,0,0,0.5)'

    },
    container: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    h3: {
        position: 'absolute',
        width: '100%',
        height: '100%',
        top: '0',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
        paddingTop: '150px',
        fontFamily: 'Poppins, sans-serif',
        textShadow: '2px 2px 4px rgba(0,0,0,0.5)'

    },
    centerObject : {
        display : 'flex',
        justifyContent: 'center',
        alignItems : 'center',
    },
    conference: {
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
        fontFamily: 'Montserrat, sans-serif',
        textShadow: '2px 2px 4px rgba(0,0,0,0.5)'
    },
    boxHeader: {
        display: "flex",
        gap: "1rem",
        color: 'white',
        fontWeight: '500',
        fontFamily: 'Poppins',
        marginRight: '5%',
    },
    region: {
        width: '100%',
        height: '100%',
        top: '0%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: '#1c1c1c',
        padding: '5%',
        fontFamily: 'Poppins, sans-serif',
        textShadow: '1px 1px 2px rgba(0,0,0,0.5)',
    },
    headerText: {
        textTransform: "none",
        color: 'white',
        fontSize: '25px',
        fontWeight: 'bold',
        fontFamily: 'Poppins',
        textDecoration: 'none',
    },
    eachButton: {
        textTransform: "none",
        marginRight: '10%',
        color: 'white',
        fontSize: '25px',
        fontWeight: '500',
        fontFamily: 'Poppins',
        textDecoration: 'none',
    },
    footerText: {
        textTransform: "none",
        color: 'white',
        fontSize: '18px',
        fontWeight: '500',
        fontFamily: 'Poppins',
        textDecoration: 'none',
    },
    headerButton: {
        marginRight: '20%',
        fontSize: '18px',
        fontWeight: '500',
        fontFamily: 'Poppins',
        textDecoration: 'none',
    },
    teams: {
        color: 'white',
        fontSize: '30px',
        fontWeight: '500',
        fontFamily: 'Poppins',
        borderColor: 'white',
        borderWidth: '3px',
        float: 'left',
        textDecoration: 'underline',
        textDecorationThickness : '1px',
        textUnderlineOffset : '12px',
        padding:"5%",
    },
    switchConference : {
        display: 'inline-block',
        position: 'flex',
        color: 'white',
        borderColor: 'white',
        borderWidth: '3px',
        fontFamily: 'Poppins, sans-serif',
        textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
        top: '0%',
        marginTop: '5%',
    },
    standings: {
        color: 'white',
        fontSize: '50px',
        fontWeight: '500',
        fontFamily: 'Poppins',
        borderColor: 'white',
        borderWidth: '3px',
        float: 'left',
        display: 'inline-block',
    },
    logo: {
        opacity: '1',
        display: 'block',
        width: '3%',
        height: 'auto',
        transition: '.5s ease',
        backfaceVisibility: 'hidden',
        marginLeft: '1%',
    },
    row : {
        margin: '8px',
    },
    root: {
        maxWidth: 345,
    },
    media: {
        height: 200,
    },
};
export default styles;
